# Generated by Django 5.2.8 on 2025-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('cashier', 'Caissier'), ('pharmacist', 'Pharmacien')], default='cashier', max_length=20, verbose_name='Rôle'),
        ),
    ]
