# Generated by Django 5.2.8 on 2025-11-14 14:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from datetime import date, timedelta
from decimal import Decimal
from django.db import migrations, models


def migrate_stockmovements_to_lots(apps, schema_editor):
    """
    Migre les StockMovement existants vers le nouveau système de lots.
    Pour chaque produit avec des mouvements, crée un lot par défaut.
    """
    StockMovement = apps.get_model('catalog', 'StockMovement')
    Lot = apps.get_model('catalog', 'Lot')
    Product = apps.get_model('catalog', 'Product')
    PurchaseOrder = apps.get_model('catalog', 'PurchaseOrder')
    Supplier = apps.get_model('catalog', 'Supplier')
    
    # Créer un supplier et purchase_order par défaut pour la migration
    default_supplier, _ = Supplier.objects.get_or_create(
        name='Migration automatique',
        defaults={}
    )
    
    default_purchase_order, _ = PurchaseOrder.objects.get_or_create(
        supplier=default_supplier,
        status='received',
        defaults={
            'order_date': django.utils.timezone.now(),
            'receipt_date': django.utils.timezone.now(),
            'notes': 'Commande créée automatiquement lors de la migration'
        }
    )
    
    # Grouper les mouvements par produit
    movements_by_product = {}
    for movement in StockMovement.objects.filter(lot__isnull=True).select_related('product'):
        product_id = movement.product_id
        if product_id not in movements_by_product:
            movements_by_product[product_id] = []
        movements_by_product[product_id].append(movement)
    
    # Créer des lots pour chaque produit
    for product_id, movements in movements_by_product.items():
        try:
            product = Product.objects.get(pk=product_id)
        except Product.DoesNotExist:
            continue
        
        # Récupérer les valeurs du produit (qui existent encore à ce stade de la migration)
        expiration_date = getattr(product, 'expiration_date', None)
        if not expiration_date:
            expiration_date = date.today() + timedelta(days=365)
        
        stock_quantity = getattr(product, 'stock_quantity', 0) or 0
        purchase_price = getattr(product, 'purchase_price', Decimal('0.00')) or Decimal('0.00')
        sale_price = getattr(product, 'sale_price', Decimal('0.00')) or Decimal('0.00')
        
        # Créer un lot par défaut pour ce produit
        lot = Lot.objects.create(
            purchase_order=default_purchase_order,
            product=product,
            quantity=stock_quantity,
            remaining_quantity=stock_quantity,
            expiration_date=expiration_date,
            purchase_price=purchase_price,
            sale_price=sale_price,
            batch_number=f'MIGRATION-{product_id}',
            is_active=True,
        )
        
        # Assigner ce lot à tous les mouvements de ce produit
        StockMovement.objects.filter(
            product_id=product_id,
            lot__isnull=True
        ).update(lot=lot)


def reverse_migrate_stockmovements(apps, schema_editor):
    """
    Opération inverse : ne fait rien car on ne peut pas restaurer product_id
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        # Créer PurchaseOrder d'abord
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de commande')),
                ('receipt_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de réception')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('received', 'Réceptionnée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': "Commande d'achat",
                'verbose_name_plural': "Commandes d'achat",
                'ordering': ['-order_date'],
            },
        ),
        # Créer Lot ensuite
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité initiale')),
                ('remaining_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité restante')),
                ('expiration_date', models.DateField(verbose_name='Date de péremption')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Prix d'achat")),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix de vente')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de lot')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['expiration_date', 'created_at'],
            },
        ),
        # Ajouter supplier à PurchaseOrder
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='catalog.supplier', verbose_name='Fournisseur'),
        ),
        # Ajouter purchase_order à Lot
        migrations.AddField(
            model_name='lot',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.purchaseorder', verbose_name="Commande d'achat"),
        ),
        # Ajouter lot à StockMovement (nullable d'abord)
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.lot', verbose_name='Lot'),
        ),
        # Migrer les données : créer des lots pour les mouvements existants
        migrations.RunPython(migrate_stockmovements_to_lots, reverse_migrate_stockmovements),
        # Rendre lot non-nullable après la migration des données
        migrations.AlterField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.lot', verbose_name='Lot'),
        ),
        # Supprimer product de StockMovement
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        # Supprimer les champs de Product
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        # Ajouter les index
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['lot', '-movement_date'], name='catalog_sto_lot_id_f04efa_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['product', 'expiration_date', 'is_active'], name='catalog_lot_product_683691_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['is_active', 'expiration_date'], name='catalog_lot_is_acti_580828_idx'),
        ),
    ]
