# Generated by Django 5.2.8 on 2025-11-11 09:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_date'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Ligne de vente', 'verbose_name_plural': 'Lignes de vente'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde crédit'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Numéro de facture'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.sale', verbose_name='Vente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sent_email',
            field=models.BooleanField(default=False, verbose_name='Envoyée par email'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sent_sms',
            field=models.BooleanField(default=False, verbose_name='Envoyée par SMS'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte'), ('credit', 'Crédit')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Vente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant payé'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde restant'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte'), ('credit', 'Crédit')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de vente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('paid', 'Payée'), ('partial', 'Partielle')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Sous-total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Taxe'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total TTC'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total ligne'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Vente'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire'),
        ),
    ]
