# Generated by Django 5.2.8 on 2025-11-14 14:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_purchaseorder_remove_product_expiration_date_and_more'),
        ('sales', '0002_alter_customer_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Virement bancaire'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant payé'),
        ),
        migrations.CreateModel(
            name='SaleItemLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_item_lots', to='catalog.lot', verbose_name='Lot')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_items', to='sales.saleitem', verbose_name='Ligne de vente')),
            ],
            options={
                'verbose_name': 'Lot de ligne de vente',
                'verbose_name_plural': 'Lots de lignes de vente',
                'unique_together': {('sale_item', 'lot')},
            },
        ),
    ]
