# Generated by Django 5.2.8 on 2025-11-14 17:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant de la remise appliquée à la vente', max_digits=12, verbose_name='Remise'),
        ),
    ]
