# Generated by Django 5.2.8 on 2025-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_add_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Les clients anonymes ne sont pas listés par défaut dans les formulaires et listes', verbose_name='Client anonyme'),
        ),
    ]
