# Generated by Django 5.2.8 on 2025-11-15 01:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_is_anonymous_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'Montant'), ('percentage', 'Pourcentage')], default='amount', max_length=20, verbose_name='Type de remise'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant ou pourcentage de la remise selon le type', max_digits=12, verbose_name='Valeur de la remise'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Montant de la remise appliquée à la vente (deprecated)', max_digits=12, verbose_name='Remise (legacy)'),
        ),
    ]
