# Generated by Django 5.2.8 on 2025-11-15 02:06

import uuid
from django.db import migrations, models
from django.utils import timezone


def generate_reference_for_existing_sales(apps, schema_editor):
    """
    Génère une référence unique pour toutes les ventes existantes qui n'en ont pas.
    """
    Sale = apps.get_model('sales', 'Sale')
    
    for sale in Sale.objects.filter(reference__isnull=True):
        # Générer une référence unique
        timestamp = timezone.now().strftime('%Y%m%d-%H%M%S')
        random_suffix = uuid.uuid4().hex[:6].upper()
        reference = f'SALE-{timestamp}-{random_suffix}'
        
        # Vérifier l'unicité (au cas où)
        while Sale.objects.filter(reference=reference).exists():
            random_suffix = uuid.uuid4().hex[:6].upper()
            reference = f'SALE-{timestamp}-{random_suffix}'
        
        sale.reference = reference
        sale.save(update_fields=['reference'])


def reverse_migrate(apps, schema_editor):
    """
    Migration inverse : ne fait rien, on garde les références.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_migrate_discount_amount_to_type_value'),
    ]

    operations = [
        # Étape 1 : Ajouter le champ comme nullable et non-unique
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(
                blank=True,
                help_text='Référence unique de la vente',
                max_length=100,
                null=True,
                verbose_name='Référence',
            ),
        ),
        # Étape 2 : Générer les références pour les ventes existantes
        migrations.RunPython(generate_reference_for_existing_sales, reverse_migrate),
        # Étape 3 : Rendre le champ unique (mais toujours nullable pour permettre blank=True)
        migrations.AlterField(
            model_name='sale',
            name='reference',
            field=models.CharField(
                blank=True,
                help_text='Référence unique de la vente',
                max_length=100,
                null=True,
                unique=True,
                verbose_name='Référence',
            ),
        ),
    ]
