# Generated by Django 5.2.8 on 2025-11-15 02:22

from django.db import migrations, models


def change_draft_to_pending(apps, schema_editor):
    """
    Change tous les statuts 'draft' en 'pending'.
    """
    Sale = apps.get_model('sales', 'Sale')
    Sale.objects.filter(status='draft').update(status='pending')


def reverse_migrate(apps, schema_editor):
    """
    Migration inverse : remet 'pending' en 'draft'.
    """
    Sale = apps.get_model('sales', 'Sale')
    Sale.objects.filter(status='pending').update(status='draft')


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_reference'),
    ]

    operations = [
        # D'abord, convertir les données 'draft' en 'pending'
        migrations.RunPython(change_draft_to_pending, reverse_migrate),
        # Ensuite, modifier le champ pour changer les choix et la valeur par défaut
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('partial', 'Partielle')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
